jeromekelleher/sc2ts-paper

data/README.md, plot.py
Requires https://github.com/jeromekelleher/sc2ts/pull/112. Here's the current PDF it produces:
[cophylogeny.pdf](https://github.com/jeromekelleher/sc2ts-paper/files/10889741/cophylogeny.pdf)
Note that the SVG is somewhat more interactive, as it allows samples labels to be revealed on hover
=> Add code to produce the cophylogeny plot

paper.tex
Create stub sections for discussing the results about Pango X lineages
=> Reorder results section

paper.tex
Various tweaks to tabular data, and rough additions from a presentation I gave
=> Table tweaks

paper.tex
=> Updates to figures and display items

paper.tex
=> Add caption for cophylogeny plot

paper.bib, paper.tex
=> Some extra tskit usage refs.

paper.tex
=> Remove spaces

notebooks/s2.1_summary_tables.ipynb, paper.tex
=> Sort out mutations

paper.tex
=> Remove unhelpful UPGMAs and edge counts

paper.tex
=> Reset hyperlinks

README.md
=> Update README.md - add virological link

scripts/run_lineage_imputation.py
And revert to chained assignment behaviour until I can figure out why the correct alternative isn't working
=> Add in functions removed from the sc2ts repo

.gitignore, viridian_dataset/Snakefile
=> Add zarr output to viridian pipeline

scripts/run_lineage_imputation.py, scripts/run_nonsample_dating.py
And default to storing the mutation time
=> Add provenance to scripts

notebooks/nb_utils.py
These are for colouring plots etc.
=> Add some useful utility functions for notebooks

notebooks/match_pango_x_absent_in_arg.ipynb
=> Examine matching results for complex Pango Xs

notebooks/nb_utils.py
Nicer dates, standard colours, etc.
=> Add a few more functions to the utils file

.gitignore, src/mat2tsk.py, usher_tree/README.md, usher_tree/Snakefile
And also allow a docker image of usher to be used (easiest way to get this working on my machine).
Fixes #444
=> Update Usher snakefile to run tsdate

notebooks/nb_utils.py
=> Restore accidentally deleted notebook functions

data/bigtable_pangodesig.csv
**XAU**
I think the RecombinHunt authors made a typo, and didn't adjust the left coordinate.
**XBT**
I mistakenly didn't add the breakpoint intervals.
=> Adjust and add breakpoint intervals

latex/main.tex
Opening this for visibility, but shelving for now
=> Start on finalising mapping details

latex/main.tex
=> Minor edits

latex/main.tex, latex/references.bib
Here's a first pass at the authorship list. I've just copied the list from the preprint and added @IsobelGuthrie to the list of middle authors in alphabetical order.
I've not added additional details like corresponding and joint second etc - we can discuss on Slack
=> First pass at authorship

requirements.txt
=> Update tskit and tskit_arg_visualizer versions

notebooks/tab_deletions.ipynb
=> Get sample support per deletion
